INSERT INTO Topics
	(id, subjectID, topic, clickThroughCount) 
VALUES 
	-- (1, 'algorithms and data structures', 0),
	(1, 1, 'red black trees', 0),
	-- (2, 'automata theory', 0),
	(2, 2, 'deterministic finite state machines', 0),
	-- (3, 'calculus 1 (differential)', 0),
	(3, 3, 'limits', 0),
	-- (4, 'calculus 2 (integral)', 0),
	(4, 4, 'integrating trigonometric functions', 0),
	-- (5, 'computer architecture', 0),
	(6, 5, 'X86 assembly language', 0),
	(7, 6, 'MIPS assembly language', 0),
	-- (6, 'digital logic', 0),
	(8, 7, 'Digital Logic place holder', 0),
	-- (7, 'discrete mathematics', 0),
	(9, 8, 'planar graphs', 0),
	-- (8, 'introductory programming', 0),
	(10, 9, 'basic control structures', 0),
	-- (9, 'linear algebra', 0),
	(11, 10, 'matrix multiplication', 0),
	-- (10, 'machine learning', 0),
	(12, 11, 'machine learning place holder', 0),
	-- (11, 'object oriented programming', 0),
	(13, 12, 'objects in java', 0),
	(14, 13, 'objects in c++', 0),
	-- (12, 'operating system concepts', 0),
	(15, 14, 'os concepts placeholder', 0),
	-- (13, 'organization of programming languages', 0),
	(16, 15, 'lhs parse trees', 0),
	-- (14, 'physics mechanics and heat', 0),
	(17, 16, 'newtons equations of motion', 0),
	-- (15, 'physics electromagnetism and waves', 0),
	(18, 17, 'circuits: capacitance, voltage, current, resistance, induction', 0),
	-- (16, 'probability and statistics', 0),
	(19, 18, 'bayes theorem', 0),
	-- (17, 'software engineering', 0)
	(20, 19, 'requirements', 0);